=== Fredilly/article6-methodologies/schemas/tools.meta.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": ["id", "version", "assets", "references", "audit"],
  "properties": {
    "id": {
      "type": "string",
      "minLength": 1
    },
    "version": {
      "type": "string",
      "minLength": 1
    },
    "audit": {
      "type": "object",
      "additionalProperties": false,
      "required": ["created_at", "created_by"],
      "properties": {
        "created_at": {
          "type": "string",
          "minLength": 1
        },
        "created_by": {
          "type": "string",
          "minLength": 1
        },
        "source_commit": {
          "type": ["string", "null"],
          "minLength": 1
        }
      }
    },
    "references": {
      "type": "object",
      "additionalProperties": false,
      "required": ["methodology"],
      "properties": {
        "methodology": {
          "type": "string",
          "minLength": 1
        },
        "meta_path": {
          "type": "string",
          "minLength": 1
        },
        "doc": {
          "type": ["string", "null"]
        },
        "url": {
          "type": ["string", "null"]
        }
      }
    },
    "assets": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["path", "sha256", "kind", "bytes"],
        "properties": {
          "path": {
            "type": "string",
            "minLength": 1
          },
          "kind": {
            "type": "string",
            "minLength": 1
          },
          "sha256": {
            "type": "string",
            "pattern": "^[0-9a-f]{64}$"
          },
          "bytes": {
            "type": "integer",
            "minimum": 0
          },
          "size": {
            "type": "integer",
            "minimum": 0
          },
          "doc": {
            "type": ["string", "null"]
          },
          "url": {
            "type": ["string", "null"]
          },
          "lfs": {
            "type": "boolean"
          }
        }
      }
    }
  }
}

=== Fredilly/article6-methodologies/tools/UNFCCC/Forestry/AR-AM0014/v02-0/META.json
{
  "id": "UNFCCC.Forestry.AR-AM0014",
  "version": "v02-0",
  "audit": {
    "created_at": "2025-11-06T10:01:57Z",
    "created_by": "scripts/generate-tools-meta.js",
    "source_commit": "ae215a5daa98f2764370a599e03acebbe7d77dbd"
  },
  "references": {
    "methodology": "UNFCCC.Forestry.AR-AM0014@v02-0",
    "meta_path": "methodologies/UNFCCC/Forestry/AR-AM0014/v02-0/META.json",
    "doc": null,
    "url": null
  },
  "assets": [
    {
      "path": "tools/UNFCCC/Forestry/AR-AM0014/v02-0/source.pdf",
      "kind": "pdf",
      "sha256": "d4656f9d29fe9afbe35e2fda7dfadf0e5b80220b56319980c18147c8b8dcb955",
      "bytes": 180228,
      "size": 180228,
      "doc": "UNFCCC/AR-AM0014@v02.0",
      "url": null,
      "lfs": true
    }
  ]
}

=== Fredilly/article6-methodologies/tools/UNFCCC/Agriculture/AMS-III/R/v05-0/META.json
{
  "id": "UNFCCC.Agriculture.AMS-III.R",
  "version": "v05-0",
  "audit": {
    "created_at": "2025-11-06T10:57:04Z",
    "created_by": "scripts/generate-tools-meta.js",
    "source_commit": "ae215a5daa98f2764370a599e03acebbe7d77dbd"
  },
  "references": {
    "methodology": "UNFCCC.Agriculture.AMS-III.R@v05-0",
    "meta_path": "methodologies/UNFCCC/Agriculture/AMS-III/R/v05-0/META.json",
    "doc": null,
    "url": "https://cdm.unfccc.int/methodologies/DB/Q8EMKMK67G1XIUKJFED8EVFL2VH1SN"
  },
  "assets": [
    {
      "path": "tools/UNFCCC/Agriculture/AMS-III/R/v05-0/Baseline-project-and-or-leakage-emissions-from-electricity-consumption-and-monitoring-of-electricity-generation.pdf",
      "kind": "pdf",
      "sha256": "b292e66001d2e854af3176e4f922ce922cb6faa426d88f6071a2f1a64f353c51",
      "bytes": 572432,
      "size": 572432,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Agriculture/AMS-III/R/v05-0/Demonstration-of-additionality-of-small-scale-project-activities.pdf",
      "kind": "pdf",
      "sha256": "c3a9fbb19b500f6ab70dfd29c3765921bb348251c8c7387e20ed50f96b29993d",
      "bytes": 205794,
      "size": 205794,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Agriculture/AMS-III/R/v05-0/Leakage-in-biomass-small-scale-project-activities.pdf",
      "kind": "pdf",
      "sha256": "13a14ce8ae638e0b2ae87873c854d60e8b129934611a4d41f2ac6d10caae03df",
      "bytes": 115899,
      "size": 115899,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Agriculture/AMS-III/R/v05-0/Project-and-leakage-emissions-from-anaerobic-digesters.pdf",
      "kind": "pdf",
      "sha256": "0788effccd28e867dfee522e5c413ca4d47240c75acce3a05d6d0cf759a3d1d0",
      "bytes": 325737,
      "size": 325737,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Agriculture/AMS-III/R/v05-0/source.pdf",
      "kind": "pdf",
      "sha256": "30981a72628c9317aeeb1a33aa61651825b02c9bcccae3d9b0d15bf071a762bb",
      "bytes": 293350,
      "size": 293350,
      "doc": "UNFCCC/R@v05.0",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Agriculture/AMS-III/R/v05-0/Tool-to-calculate-project-or-leakage-CO2-emissions-from-fossil-fuel-combustion.pdf",
      "kind": "pdf",
      "sha256": "64bb83daec11116f8eaab00ca0d03ecdcb41be64076976b972d774b267ca6e02",
      "bytes": 447750,
      "size": 447750,
      "doc": "",
      "url": null,
      "lfs": true
    }
  ]
}

=== Fredilly/article6-methodologies/tools/UNFCCC/Forestry/AR-AMS0003/v02-0/META.json
{
  "id": "UNFCCC.Forestry.AR-AMS0003",
  "version": "v02-0",
  "audit": {
    "created_at": "2025-11-06T10:02:41Z",
    "created_by": "scripts/generate-tools-meta.js",
    "source_commit": "ae215a5daa98f2764370a599e03acebbe7d77dbd"
  },
  "references": {
    "methodology": "UNFCCC.Forestry.AR-AMS0003@v02-0",
    "meta_path": "methodologies/UNFCCC/Forestry/AR-AMS0003/v02-0/META.json",
    "doc": null,
    "url": null
  },
  "assets": [
    {
      "path": "tools/UNFCCC/Forestry/AR-AMS0003/v02-0/source.pdf",
      "kind": "pdf",
      "sha256": "fb93c1b522e3439d97aace522ea9f990d69976e79afb3723013e24d92fe7b3fa",
      "bytes": 237872,
      "size": 237872,
      "doc": "UNFCCC/AR-AMS0003@v02.0",
      "url": null,
      "lfs": true
    }
  ]
}

=== Fredilly/article6-methodologies/tools/UNFCCC/Agriculture/AMS-III/D/v21-0/META.json
{
  "id": "UNFCCC.Agriculture.AMS-III.D",
  "version": "v21-0",
  "audit": {
    "created_at": "2025-11-06T10:56:51Z",
    "created_by": "scripts/generate-tools-meta.js",
    "source_commit": "ae215a5daa98f2764370a599e03acebbe7d77dbd"
  },
  "references": {
    "methodology": "UNFCCC.Agriculture.AMS-III.D@v21-0",
    "meta_path": "methodologies/UNFCCC/Agriculture/AMS-III/D/v21-0/META.json",
    "doc": null,
    "url": "https://cdm.unfccc.int/methodologies/DB/H9DVSB24O7GEZQYLYNWUX23YS6G4RC"
  },
  "assets": [
    {
      "path": "tools/UNFCCC/Agriculture/AMS-III/D/v21-0/Baseline-project-and-or-leakage-emissions-from-electricity-consumption-and-monitoring-of-electricity-generation.pdf",
      "kind": "pdf",
      "sha256": "b292e66001d2e854af3176e4f922ce922cb6faa426d88f6071a2f1a64f353c51",
      "bytes": 572432,
      "size": 572432,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Agriculture/AMS-III/D/v21-0/Project-and-leakage-emissions-from-anaerobic-digesters.pdf",
      "kind": "pdf",
      "sha256": "0788effccd28e867dfee522e5c413ca4d47240c75acce3a05d6d0cf759a3d1d0",
      "bytes": 325737,
      "size": 325737,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Agriculture/AMS-III/D/v21-0/Project-emissions-from-flaring.pdf",
      "kind": "pdf",
      "sha256": "0a806611660fab64122335bd85c8c20974c8932b3e063592692b7d2230162907",
      "bytes": 426246,
      "size": 426246,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Agriculture/AMS-III/D/v21-0/source.pdf",
      "kind": "pdf",
      "sha256": "a9c6c73c84f2bc3bbde7ccdac996accadec15f33cb2da10cd95227ac8373a4c4",
      "bytes": 853732,
      "size": 853732,
      "doc": "UNFCCC/D@v21.0",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Agriculture/AMS-III/D/v21-0/Tool-to-calculate-project-or-leakage-CO2-emissions-from-fossil-fuel-combustion.pdf",
      "kind": "pdf",
      "sha256": "64bb83daec11116f8eaab00ca0d03ecdcb41be64076976b972d774b267ca6e02",
      "bytes": 447750,
      "size": 447750,
      "doc": "",
      "url": null,
      "lfs": true
    }
  ]
}

=== Fredilly/article6-methodologies/tools/GoldStandard/LUF/GS-00XX/v1-0/META.json
{
  "id": "GoldStandard.LUF.GS-00XX",
  "version": "v1-0",
  "audit": {
    "created_at": "1970-01-01T00:00:00Z",
    "created_by": "scripts/generate-tools-meta.js",
    "source_commit": "ae215a5daa98f2764370a599e03acebbe7d77dbd"
  },
  "references": {
    "methodology": "GoldStandard.LUF.GS-00XX@v1-0",
    "meta_path": "methodologies/GoldStandard/LUF/GS-00XX/v1-0/META.json",
    "doc": null,
    "url": null
  },
  "assets": [
    {
      "path": "tools/GoldStandard/LUF/GS-00XX/v1-0/source.pdf",
      "kind": "pdf",
      "sha256": "5a838678058f6de375e8635b5f2fea47a4e5f07cb1a882a44b10f39abc6f34ff",
      "bytes": 45,
      "size": 45,
      "doc": "GoldStandard/GS-00XX@v1.0",
      "url": null,
      "lfs": true
    }
  ]
}

=== Fredilly/article6-methodologies/tools/UNFCCC/Forestry/AR-AMS0007/v03-1/META.json
{
  "id": "UNFCCC.Forestry.AR-AMS0007",
  "version": "v03-1",
  "audit": {
    "created_at": "2025-11-06T10:03:04Z",
    "created_by": "scripts/generate-tools-meta.js",
    "source_commit": "ae215a5daa98f2764370a599e03acebbe7d77dbd"
  },
  "references": {
    "methodology": "UNFCCC.Forestry.AR-AMS0007@v03-1",
    "meta_path": "methodologies/UNFCCC/Forestry/AR-AMS0007/v03-1/META.json",
    "doc": null,
    "url": "https://cdm.unfccc.int/methodologies/DB/J6ZHLX1C3AEMSZ52PWIII6D2AOJZUB"
  },
  "assets": [
    {
      "path": "tools/UNFCCC/Forestry/AR-AMS0007/v03-1/ar-am-tool-02-v1.pdf",
      "kind": "pdf",
      "sha256": "37324fd7d9e727d006bd7e46b5410acff24acbe2195a65229a70a27041bbe4b4",
      "bytes": 251692,
      "size": 251692,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AMS0007/v03-1/ar-am-tool-08-v4.0.0.pdf",
      "kind": "pdf",
      "sha256": "c54deaf3cbe89fa8765ec34af186400e74c08545de646d41af7a93a50565e397",
      "bytes": 263864,
      "size": 263864,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AMS0007/v03-1/ar-am-tool-12-v3.1.pdf",
      "kind": "pdf",
      "sha256": "b921a0a3b5c1e2e8791526b0ca0e183ca81dd35db59e515bb89771af692863f4",
      "bytes": 275971,
      "size": 275971,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AMS0007/v03-1/ar-am-tool-14-v4.2.pdf",
      "kind": "pdf",
      "sha256": "b63fccecaf7730e9f1d461ef51cefea2252e89dbb5a630869c9e265b23577331",
      "bytes": 691428,
      "size": 691428,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AMS0007/v03-1/ar-am-tool-15-v2.0.pdf",
      "kind": "pdf",
      "sha256": "b8e0252fc7bcfadc184dbb2dab12205c85d6d4af5a291b39128bd861ab878e29",
      "bytes": 1008516,
      "size": 1008516,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AMS0007/v03-1/ar-am-tool-16-v1.1.0.pdf",
      "kind": "pdf",
      "sha256": "edc718dba7eb097092907553f849c10a36e91a3b4199677ccf4a78748a92f8de",
      "bytes": 255568,
      "size": 255568,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AMS0007/v03-1/AR-TOOL08_v4-0-0.pdf",
      "kind": "pdf",
      "sha256": "c54deaf3cbe89fa8765ec34af186400e74c08545de646d41af7a93a50565e397",
      "bytes": 263864,
      "size": 263864,
      "doc": "UNFCCC/AR-TOOL08@v4.0.0",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AMS0007/v03-1/AR-TOOL12_v3-1.pdf",
      "kind": "pdf",
      "sha256": "b921a0a3b5c1e2e8791526b0ca0e183ca81dd35db59e515bb89771af692863f4",
      "bytes": 275971,
      "size": 275971,
      "doc": "UNFCCC/AR-TOOL12@v3.1",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AMS0007/v03-1/AR-TOOL14_v4-2.pdf",
      "kind": "pdf",
      "sha256": "b63fccecaf7730e9f1d461ef51cefea2252e89dbb5a630869c9e265b23577331",
      "bytes": 691428,
      "size": 691428,
      "doc": "UNFCCC/AR-TOOL14@v4.2",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AMS0007/v03-1/AR-TOOL15_v2-0.pdf",
      "kind": "pdf",
      "sha256": "b8e0252fc7bcfadc184dbb2dab12205c85d6d4af5a291b39128bd861ab878e29",
      "bytes": 1008516,
      "size": 1008516,
      "doc": "UNFCCC/AR-TOOL15@v2.0",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AMS0007/v03-1/AR-TOOL16_v1-1-0.pdf",
      "kind": "pdf",
      "sha256": "edc718dba7eb097092907553f849c10a36e91a3b4199677ccf4a78748a92f8de",
      "bytes": 255568,
      "size": 255568,
      "doc": "UNFCCC/AR-TOOL16@v1.1.0",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AMS0007/v03-1/CDM-glossary.pdf",
      "kind": "pdf",
      "sha256": "62cbedc1d4fb3e66b9b37eb6ad2225eb998fad36aecdd20444095d7d46687e5c",
      "bytes": 277555,
      "size": 277555,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AMS0007/v03-1/Estimation-of-carbon-stocks-and-change-in-carbon-stocks-in-dead-wood-and-litter-in-A-R-CDM-project-activities.pdf",
      "kind": "pdf",
      "sha256": "b921a0a3b5c1e2e8791526b0ca0e183ca81dd35db59e515bb89771af692863f4",
      "bytes": 275971,
      "size": 275971,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AMS0007/v03-1/Estimation-of-carbon-stocks-and-change-in-carbon-stocks-of-trees-and-shrubs-in-A-RCDM-project-activities.pdf",
      "kind": "pdf",
      "sha256": "b63fccecaf7730e9f1d461ef51cefea2252e89dbb5a630869c9e265b23577331",
      "bytes": 691428,
      "size": 691428,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AMS0007/v03-1/Estimation-of-non-CO2-GHG-emissions-resulting-from-burning-of-biomass-attributable-to-an-A-R-CDM-project-activity.pdf",
      "kind": "pdf",
      "sha256": "c54deaf3cbe89fa8765ec34af186400e74c08545de646d41af7a93a50565e397",
      "bytes": 263864,
      "size": 263864,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AMS0007/v03-1/Estimation-of-the-increase-in-GHG-emissions-attributable-to-displacement-of-pre-project-agricultural-activities-in-A-R-CDM-project-activity.pdf",
      "kind": "pdf",
      "sha256": "b8e0252fc7bcfadc184dbb2dab12205c85d6d4af5a291b39128bd861ab878e29",
      "bytes": 1008516,
      "size": 1008516,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AMS0007/v03-1/source.docx",
      "kind": "docx",
      "sha256": "2f73349cfc4630255319c6c8dfc1b46a8996ace9d14d8e07563b165915918ec2",
      "bytes": 12,
      "size": 12,
      "doc": "UNFCCC/AR-AMS0007@v03.1",
      "url": null,
      "lfs": false
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AMS0007/v03-1/source.pdf",
      "kind": "pdf",
      "sha256": "2facdc8509c8dd2c7da4ca884cec431ab9d7ceb6ec628decc330e550cbcf2bc9",
      "bytes": 209654,
      "size": 209654,
      "doc": "UNFCCC/AR-AMS0007@v03.1",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AMS0007/v03-1/Tool-for-estimation-of-change-in-soil-organic-carbon-stocks-due-to-the-implementation-of-A-R-CDM-project-activities.pdf",
      "kind": "pdf",
      "sha256": "edc718dba7eb097092907553f849c10a36e91a3b4199677ccf4a78748a92f8de",
      "bytes": 255568,
      "size": 255568,
      "doc": "",
      "url": null,
      "lfs": true
    }
  ]
}

=== Fredilly/article6-methodologies/tools/UNFCCC/Forestry/AR-AM0014/v03-0/META.json
{
  "id": "UNFCCC.Forestry.AR-AM0014",
  "version": "v03-0",
  "audit": {
    "created_at": "2025-11-06T10:01:51Z",
    "created_by": "scripts/generate-tools-meta.js",
    "source_commit": "ae215a5daa98f2764370a599e03acebbe7d77dbd"
  },
  "references": {
    "methodology": "UNFCCC.Forestry.AR-AM0014@v03-0",
    "meta_path": "methodologies/UNFCCC/Forestry/AR-AM0014/v03-0/META.json",
    "doc": null,
    "url": "https://cdm.unfccc.int/methodologies/DB/KMH6O8T6RL3P5XKNBQE2N359QG7KOE"
  },
  "assets": [
    {
      "path": "tools/UNFCCC/Forestry/AR-AM0014/v03-0/ar-am-tool-02-v1.pdf",
      "kind": "pdf",
      "sha256": "37324fd7d9e727d006bd7e46b5410acff24acbe2195a65229a70a27041bbe4b4",
      "bytes": 251692,
      "size": 251692,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AM0014/v03-0/ar-am-tool-08-v4.0.0.pdf",
      "kind": "pdf",
      "sha256": "c54deaf3cbe89fa8765ec34af186400e74c08545de646d41af7a93a50565e397",
      "bytes": 263864,
      "size": 263864,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AM0014/v03-0/ar-am-tool-12-v3.1.pdf",
      "kind": "pdf",
      "sha256": "b921a0a3b5c1e2e8791526b0ca0e183ca81dd35db59e515bb89771af692863f4",
      "bytes": 275971,
      "size": 275971,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AM0014/v03-0/ar-am-tool-14-v4.2.pdf",
      "kind": "pdf",
      "sha256": "b63fccecaf7730e9f1d461ef51cefea2252e89dbb5a630869c9e265b23577331",
      "bytes": 691428,
      "size": 691428,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AM0014/v03-0/ar-am-tool-15-v2.0.pdf",
      "kind": "pdf",
      "sha256": "b8e0252fc7bcfadc184dbb2dab12205c85d6d4af5a291b39128bd861ab878e29",
      "bytes": 1008516,
      "size": 1008516,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AM0014/v03-0/CDM-glossary.pdf",
      "kind": "pdf",
      "sha256": "62cbedc1d4fb3e66b9b37eb6ad2225eb998fad36aecdd20444095d7d46687e5c",
      "bytes": 277555,
      "size": 277555,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AM0014/v03-0/Combined-tool-to-identify-the-baseline-scenario-and-demonstrate-additionality-in-A-R-CDM-project-activities.pdf",
      "kind": "pdf",
      "sha256": "37324fd7d9e727d006bd7e46b5410acff24acbe2195a65229a70a27041bbe4b4",
      "bytes": 251692,
      "size": 251692,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AM0014/v03-0/EB75_repan29_AR-AM0014_ver03.0.pdf",
      "kind": "pdf",
      "sha256": "5484c0392761c9d7b4cca9e3f66e8e72d353fff371da45cb0ba2a3d254b8eb1a",
      "bytes": 1131963,
      "size": 1131963,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AM0014/v03-0/Estimation-of-carbon-stocks-and-change-in-carbon-stocks-in-dead-wood-and-litter-in-A-R-CDM-project-activities.pdf",
      "kind": "pdf",
      "sha256": "b921a0a3b5c1e2e8791526b0ca0e183ca81dd35db59e515bb89771af692863f4",
      "bytes": 275971,
      "size": 275971,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AM0014/v03-0/Estimation-of-carbon-stocks-and-change-in-carbon-stocks-of-trees-and-shrubs-in-A-RCDM-project-activities.pdf",
      "kind": "pdf",
      "sha256": "b63fccecaf7730e9f1d461ef51cefea2252e89dbb5a630869c9e265b23577331",
      "bytes": 691428,
      "size": 691428,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AM0014/v03-0/Estimation-of-non-CO2-GHG-emissions-resulting-from-burning-of-biomass-attributable-to-an-A-R-CDM-project-activity.pdf",
      "kind": "pdf",
      "sha256": "c54deaf3cbe89fa8765ec34af186400e74c08545de646d41af7a93a50565e397",
      "bytes": 263864,
      "size": 263864,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AM0014/v03-0/Estimation-of-the-increase-in-GHG-emissions-attributable-to-displacement-of-pre-project-agricultural-activities-in-A-R-CDM-project-activity.pdf",
      "kind": "pdf",
      "sha256": "b8e0252fc7bcfadc184dbb2dab12205c85d6d4af5a291b39128bd861ab878e29",
      "bytes": 1008516,
      "size": 1008516,
      "doc": "",
      "url": null,
      "lfs": true
    },
    {
      "path": "tools/UNFCCC/Forestry/AR-AM0014/v03-0/source.pdf",
      "kind": "pdf",
      "sha256": "5484c0392761c9d7b4cca9e3f66e8e72d353fff371da45cb0ba2a3d254b8eb1a",
      "bytes": 1131963,
      "size": 1131963,
      "doc": "UNFCCC/AR-AM0014@v03.0",
      "url": null,
      "lfs": true
    }
  ]
}
